### ISSUE TITLE
A question about "cloud_bin_*.keypts.npy"

### ISSUE THREAD

**Issue by QWTforGithub** [craigleili/3DLocalMultiViewDesc#4]
Hi , thank you for your last reply. Now,I have a new question about "cloud_bin_*.keypts.npy".
I run this code : 
     python main_mvdesc.py test configs/ours_3dmatch.yaml
The problem is :
     FileNotFoundError: [Errno 2] No such file or directory: '../../3DMatch_test/7-scenes-redkitchen/seq-01/cloud_bin_0.keypts.npy'
How do I generate the file cloud_bin_*.keypts.npy? I seemed to can not find the file to generate it.
Oh, one more question, what is the 'desc_types' in eval_geomreg_3dmatch.py in evaluation folder? Is it a path?
     Looking forward your reply.
     Best wish.

**Comment by craigleili** [comment]
Hello,

For the processed data, please have a check at the download link at https://github.com/craigleili/3DLocalMultiViewDesc#evaluation
The ```desc_types``` is a list of folder names (not paths) for the descriptors. Please see the script ```eval_geomreg_3dmatch.sh```.

All the best
