### ISSUE TITLE
Can you give the data from 0.00-0.20 results

### ISSUE THREAD

**Issue by QWTforGithub** [craigleili/3DLocalMultiViewDesc#5]
Hi,I would like to make some experimental comparisons according to your work. Could you give me the Feat Macthing Ratio from 0.00 to 0.20? The results I run by myself may not meet the requirements of the results you run, so I hope you can give me, thank you.

Looking forward your reply.

**Comment by craigleili** [comment]
Hello,

Please find the attached for the raw values.

All the best

[Fig6.zip](https://github.com/craigleili/3DLocalMultiViewDesc/files/7247170/Fig6.zip)

**Comment by QWTforGithub** [comment]
> Hello,
> 
> Please find the attached for the raw values.
> 
> All the best
> 
> [Fig6.zip](https://github.com/craigleili/3DLocalMultiViewDesc/files/7247170/Fig6.zip)

Thank for your help.

Best wish for you.

**Comment by QWTforGithub** [comment]
> Hello,
> 
> Please find the attached for the raw values.
> 
> All the best
> 
> [Fig6.zip](https://github.com/craigleili/3DLocalMultiViewDesc/files/7247170/Fig6.zip)

By the way, I hope you can also provide data on the 0.00-0.20 Inlier Distance Threshold. To be exact, r2 = 0.05, r1 from 0.00 to 0.20, I would really appreciate it if you could provide it!

**Comment by craigleili** [comment]
Hello,

Sorry, I don't have the data at hand. Can you please run the script ```eval_geomreg_3dmatch.sh``` with the provided descriptors to get those values? You can follow the instructions in the [Evaluation](https://github.com/craigleili/3DLocalMultiViewDesc#evaluation) section, and you can also find the extracted descriptors there.

All the best

**Comment by QWTforGithub** [comment]
> Hello,
> 
> Sorry, I don't have the data at hand. Can you please run the script `eval_geomreg_3dmatch.sh` with the provided descriptors to get those values? You can follow the instructions in the [Evaluation](https://github.com/craigleili/3DLocalMultiViewDesc#evaluation) section, and you can also find the extracted descriptors there.
> 
> All the best

It doesn't matter, could you please provide me with the 3DMatch descriptor generated by your best model, I can run this data by myself, thank you.

**Comment by QWTforGithub** [comment]
> Hello,
> 
> Sorry, I don't have the data at hand. Can you please run the script `eval_geomreg_3dmatch.sh` with the provided descriptors to get those values? You can follow the instructions in the [Evaluation](https://github.com/craigleili/3DLocalMultiViewDesc#evaluation) section, and you can also find the extracted descriptors there.
> 
> All the best

I found it.Thanks again for your help!
