### ISSUE TITLE
question about the "soft-view pooling"?

### ISSUE THREAD

**Issue by xfeng853** [craigleili/3DLocalMultiViewDesc#7]
Hello author, I don't understand the soft-view pooling in the paper. Can you provide some reference materials?
For example, the encoder-decoder is used in the paper to get the weight. I have no relevant knowledge, so I don't know how to get it.

**Comment by craigleili** [comment]
Hi,

The soft-view pooling is implemented [here](https://github.com/craigleili/3DLocalMultiViewDesc/blob/master/models/mvdesc.py#L52). Please have a check.

All the best

**Comment by xfeng853** [comment]
Thanks your reply,   and i have the last question. Regarding whether there is only one feature map (8×8×128, the same as the input feature map) obtained by soft view poolig, all feature maps (4n) are fused to get one. And is there only one 32-dimensional feature descriptor finally obtained?

**Comment by craigleili** [comment]
Hi,

Given `n` views of feature maps as input (e.g., `nx8×8×128`), we get a `8×8×128` feature map as output after the pooling, which is further projected to a single 32D vector.

**Comment by xfeng853** [comment]
OK，I understand。Have a good day!
