### ISSUE TITLE
A question about how to render a depth image of a complete point cloud.

### ISSUE THREAD

**Issue by QWTforGithub** [craigleili/3DLocalMultiViewDesc#8]
Thank you so much for sharing the well-organized code. I have a question about how to render a depth image of a complete point cloud. I notice that your code just renders a local depth image of a point in the point cloud. How do I change the code if I want to render the complete point cloud?
**SoftRasterizeFunc.apply(mvp_mat, vertices, radii * self.radius_ratio, colors,
                                             self.sigma, self.gamma, self.dist_ratio, self.znear,
                                             self.zfar, self.tan_half_fov, self.image_size,
                                             compute_weight, False, True)**
My understanding is that the first three parameters are more important:
  1) 8 views.
  2) The entire point cloud.
  3) I can't understand this parameter, how should I modify it?

**Comment by craigleili** [comment]
Hi,
I think you could probably manipulate the camera matrix (i.e., `mvp_mat`) to position the entire point cloud in the viewing frustum, as shown [here](https://github.com/craigleili/3DLocalMultiViewDesc/blob/master/soft_renderer/transform.py#L361).

All the best.
